### ISSUE TITLE
Problemas con desplegado

### ISSUE THREAD

**Issue by icemanmex** [kikeelectronico/Homeware-LAN#62]
Buenas tardes, antes que nada y como previo no se si sea un issue pues estoy desplegando en una orangepi y no en una Raspberry con base en esto si no se puede corregir lo entenderé. El error q me sale es al intentar levantar los servicios ya sea uno y otro. creo yo el problema esta en el archivo secure.json en cuanto a configuracion, pero no vi en ningun lado si se tenia q configurar.

pi@controlhome:/Homeware-LAN$ **sudo systemctl start homeware**
Failed to start homeware.service: Unit homeware.service is not loaded properly: Invalid argument.
See system logs and 'systemctl status homeware.service' for details.
pi@controlhome:/Homeware-LAN$ **systemctl status homeware**
● homeware.service - Homeware LAN
   **Loaded: error (Reason: Invalid argument)**
   Active: inactive (dead)
pi@controlhome:/Homeware-LAN$ **sh /home/pi/Homeware-LAN/homeware.sh**
[2020-07-08 22:46:00 +0000] [690] [INFO] Starting gunicorn 20.0.4
[2020-07-08 22:46:00 +0000] [690] [INFO] Listening at: http://0.0.0.0:5001 (690)
[2020-07-08 22:46:00 +0000] [690] [INFO] Using worker: sync
[2020-07-08 22:46:00 +0000] [693] [INFO] Booting worker with pid: 693
DDBB up and running
[2020-07-08 22:46:02 +0000] [693] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/pi/Homeware-LAN/homeware.py", line 26, in <module>
    hData = Data()
  File "/home/pi/Homeware-LAN/data.py", line 53, in __init__
    **self.userName = json.loads(self.redis.get('secure'))['user']**
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
[2020-07-08 22:46:02 +0000] [693] [INFO] Worker exiting (pid: 693)
[2020-07-08 22:46:02 +0000] [690] [INFO] Shutting down: Master
[2020-07-08 22:46:02 +0000] [690] [INFO] Reason: Worker failed to boot.

**Asi esta el archivo secure.json:**
pi@controlhome:~/Homeware-LAN$ more secure.json
{
  "key": "",
  "domain": "",
  "user": "",
  "pass": "",

Gracias y saludos desde México

**Comment by icemanmex** [comment]
Que tal Kikelectronico, 

He pasado ese primer punto, veré si puedo seguir adelante. Modifique el archivo data.py y cambie:

redis.Redis("localhost")
por
**redis.StrictRedis(host="localhost", port=6379, charset="utf-8", decode_responses=True)**

Del archivo de servicio **homeware.service** quite la linea siguiente, ya que por algún motivo marcaba error:
       _WorkingDirectory=/home/pi/Homeware-LAN/_
y de esta linea quite el "sh" quedando así:
**ExecStart=/home/pi/Homeware-LAN/homeware.sh**


Por ultimo del archivo **homeware.sh** agregue las siguientes lineas antes de ejecutar gunicorn para compensar las que se quitaron del archivo de servicio:

**SCRIPTPATH="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
cd $SCRIPTPATH**


Te iré comentando si mas adelante encuentro problemas o con eso queda, ya que dejare para mañana continuar.

**Comment by kikeelectronico** [comment]
Hace 30 días. Imagino que ya se ha solucionado el problema.
